<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37158" started-at="2015-05-07T18:03:52Z" finished-at="2015-05-07T18:04:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="37158" started-at="2015-05-07T18:03:52Z" finished-at="2015-05-07T18:04:30Z">
      <class name="com.example.tests.GroupModificationTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.GroupModificationTests@2bbaf4f0]" name="setUp" is-config="true" duration-ms="2750" started-at="2015-05-07T22:03:52Z" finished-at="2015-05-07T22:03:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="modifySomeGroup(com.example.tests.GroupData)[pri:0, instance:com.example.tests.GroupModificationTests@2bbaf4f0]" name="modifySomeGroup" duration-ms="21531" started-at="2015-05-07T22:03:55Z" data-provider="randomValidGroupGenerator" finished-at="2015-05-07T22:04:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[GroupData [groupName=hzYEyfvtZm, header=VZfltoglOHtagiqMfgWWMbAAtzJysqjJDpRmvcMhuZpKQhBJSvMhMaEiNMzimQTUlvURJqRxMmzjNHogOSzHkLWBZmKmCqWfiEjA, footer=DmQlLqMAAwiEGFKMQDKzAOqzEUBkQxyoKykSMwemawVAcDoXYHPJgIfKZOMtoVIoMCVrzZjNNCpamTELeooVGBfvamsgAfBmZXvX]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [6]: GroupData [groupName=kFVJomEUxr, header=null, footer=null] != GroupData [groupName=MKugBejSKS, header=null, footer=null] expected [GroupData [groupName=kFVJomEUxr, header=null, footer=null]] but found [GroupData [groupName=MKugBejSKS, header=null, footer=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [6]: GroupData [groupName=kFVJomEUxr, header=null, footer=null] != GroupData [groupName=MKugBejSKS, header=null, footer=null] expected [GroupData [groupName=kFVJomEUxr, header=null, footer=null]] but found [GroupData [groupName=MKugBejSKS, header=null, footer=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.GroupModificationTests.modifySomeGroup(GroupModificationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeGroup -->
        <test-method status="FAIL" signature="modifySomeGroup(com.example.tests.GroupData)[pri:0, instance:com.example.tests.GroupModificationTests@2bbaf4f0]" name="modifySomeGroup" duration-ms="8757" started-at="2015-05-07T22:04:17Z" data-provider="randomValidGroupGenerator" finished-at="2015-05-07T22:04:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[GroupData [groupName=bKrikpeqwQ, header=cPvLwqjhciABzDajgwGVTgKCmcglYEhckGiUVSjIkjKqfpillwhNFsXIZKsEMgGMsOfAJFBfGykwbapcSEwomHybRxxUZgkUCEwr, footer=]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [12]: GroupData [groupName=wfsqRtoweG, header=null, footer=null] != GroupData [groupName=WWcpVgRpAA, header=null, footer=null] expected [GroupData [groupName=wfsqRtoweG, header=null, footer=null]] but found [GroupData [groupName=WWcpVgRpAA, header=null, footer=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [12]: GroupData [groupName=wfsqRtoweG, header=null, footer=null] != GroupData [groupName=WWcpVgRpAA, header=null, footer=null] expected [GroupData [groupName=wfsqRtoweG, header=null, footer=null]] but found [GroupData [groupName=WWcpVgRpAA, header=null, footer=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.GroupModificationTests.modifySomeGroup(GroupModificationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeGroup -->
        <test-method status="FAIL" signature="modifySomeGroup(com.example.tests.GroupData)[pri:0, instance:com.example.tests.GroupModificationTests@2bbaf4f0]" name="modifySomeGroup" duration-ms="3981" started-at="2015-05-07T22:04:26Z" data-provider="randomValidGroupGenerator" finished-at="2015-05-07T22:04:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[GroupData [groupName=, header=zfIwaBzGjiQclkszhaPLYPFAirIuheBBEAhfauSQijcTHhvzKBGJJDfUvfZkOjNQMtIgFmvDgimXFYzHZbePoyNcePkCxJHgZqow, footer=IEKbqPCwZELJWFLOtyvirDFejNoNICSLbVwUQivBTtLPHifooripPlmwRohQpthJPmwyovwfBKyRxqegWzJEAYBQHdQDkoaYUxwS]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [7]: GroupData [groupName=IOlRdzhusY, header=null, footer=null] != GroupData [groupName=MKugBejSKS, header=null, footer=null] expected [GroupData [groupName=IOlRdzhusY, header=null, footer=null]] but found [GroupData [groupName=MKugBejSKS, header=null, footer=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [7]: GroupData [groupName=IOlRdzhusY, header=null, footer=null] != GroupData [groupName=MKugBejSKS, header=null, footer=null] expected [GroupData [groupName=IOlRdzhusY, header=null, footer=null]] but found [GroupData [groupName=MKugBejSKS, header=null, footer=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.GroupModificationTests.modifySomeGroup(GroupModificationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeGroup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.GroupModificationTests@2bbaf4f0]" name="tearDown" is-config="true" duration-ms="124" started-at="2015-05-07T22:04:30Z" finished-at="2015-05-07T22:04:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.GroupModificationTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
